apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: priority-classes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/wheelingsoft/speckle-infra
    targetRevision: HEAD
    path: argocd/manifests/priority-classes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
